# PAT require access to "Content"
name: Self-hosted CI

on:
  repository_dispatch:
    types: [e2e-science]

jobs:
  e2e-science:
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: |
        if [ "${{ github.event.client_payload.build }}" == "true" ]; then
          echo "build success"
        else
          echo "build failed"
          exit 1
        fi
    - name: e2e
      run: |
        if [ "${{ github.event.client_payload.e2e }}" == "true" ]; then
          echo "Succeed to run e2e tests"
        else
          echo "Failed to run e2e tests"
          exit 1
        fi
    - name: push
      run: |
        if [ "${{ github.event.client_payload.push }}" == "true" ]; then
          echo "Succeed in pushing image"
        else
          echo "Failed to push image"
          exit 1
        fi
