# PAT require access to "Content"
name: Triggered by Local Job

on:
  repository_dispatch:
    types: [e2e-science]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: success
      run: |
        if [ "${{ github.event.client_payload.unit }}" == "true" ]; then
          echo "build success"
        else
          echo "build failed"
          exit 1
        fi
